# Generated by Django 4.2.4 on 2023-08-21 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="verification_attempts",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="user",
            name="verification_code",
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
